=== lushevol/ultra-schema/src/json-schema-form/demo/ssi-form/schema/ssi-form-json-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "ssiType": {
      "title": "SSI Type",
      "type": "string",
      "enum": ["Primary", "Secondary"]
    },
    "swiftType": {
      "title": "Msg",
      "type": "string",
      "default": "MT103",
      "enum": ["MT103", "MT103 SERIAL", "MT202"]
    },
    "settlementMeans": {
      "title": "Settlement Means",
      "type": "string",
      "enum": ["CLG", "CLS SUSP", "NOS", "Over-Account", "Non-Nostro"]
    },
    "settlementAccount": {
      "title": "Settlement Account",
      "type": "string",
      "maxLength": 20
    },
    "coveredPayment": {
      "title": "Covered Payment",
      "type": "boolean"
    },
    "beneficiaryBic": {
      "title": "BIC",
      "type": "string",
      "$ref": "#/definitions/patternBicCode"
    },
    "beneficiaryName": {
      "title": "Full Name",
      "type": "string",
      "maxLength": 35,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "beneficiaryName2": {
      "title": "Full Name1",
      "type": "string",
      "maxLength": 35,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "beneficiaryAccount": {
      "title": "Account",
      "type": "string",
      "minLength": 2,
      "maxLength": 34,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "beneficiaryAddress": {
      "title": "Address",
      "type": "string",
      "maxLength": 60,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "beneficiaryCity": {
      "title": "Country",
      "type": "string",
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "tpp": {
      "title": "TPP",
      "type": "boolean"
    },
    "charges": {
      "title": "Charges",
      "type": "string",
      "enum": ["OUR", "SHA", "BEN"]
    },
    "accountWithInstitutionBic": {
      "title": "BIC",
      "type": "string",
      "$ref": "#/definitions/patternBicCode"
    },
    "accountWithInstitutionName": {
      "title": "Name",
      "type": "string",
      "maxLength": 35,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "accountWithInstitutionAccount": {
      "title": "Account",
      "type": "string",
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "accountWithInstitutionAddress": {
      "title": "Address",
      "type": "string",
      "maxLength": 60,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "accountWithInstitutionCity": {
      "title": "Country",
      "type": "string",
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "intermediaryBic": {
      "title": "BIC",
      "type": "string",
      "$ref": "#/definitions/patternBicCode"
    },
    "intermediaryName": {
      "title": "Name",
      "type": "string",
      "maxLength": 35,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "intermediaryAccount": {
      "title": "Account",
      "type": "string"
    },
    "intermediaryAddress": {
      "title": "Address",
      "type": "string",
      "maxLength": 60,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "intermediaryPostcode": {
      "title": "Country",
      "type": "string",
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "receiversCorrespondentBic": {
      "title": "BIC",
      "type": "string",
      "$ref": "#/definitions/patternBicCode"
    },
    "receiversCorrespondentName": {
      "title": "Name",
      "type": "string",
      "maxLength": 35,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "receiversCorrespondentAccount": {
      "title": "Account",
      "type": "string",
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "receiversCorrespondentAddress": {
      "title": "Address",
      "type": "string",
      "maxLength": 60,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "receiversCorrespondentCity": {
      "title": "Country",
      "type": "string",
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "orderCustomerBic": {
      "title": "BIC",
      "type": "string",
      "$ref": "#/definitions/patternBicCode"
    },
    "orderCustomerName": {
      "title": "Name",
      "type": "string",
      "maxLength": 70,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "orderCustomerAccount": {
      "title": "Account",
      "type": "string",
      "minLength": 1,
      "maxLength": 50,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "orderCustomerAddress": {
      "title": "Address",
      "type": "string",
      "maxLength": 60,
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "orderCustomerCity": {
      "title": "Country",
      "type": "string",
      "$ref": "#/definitions/patternAlphaBetNumberSpace"
    },
    "senderToReceiver1": {
      "title": "Line1",
      "type": "string",
      "maxLength": 35
    },
    "senderToReceiver2": {
      "title": "Line2",
      "type": "string",
      "maxLength": 33
    },
    "senderToReceiver3": {
      "title": "Line3",
      "type": "string",
      "maxLength": 33
    },
    "senderToReceiver4": {
      "title": "Line4",
      "type": "string",
      "maxLength": 33
    },
    "senderToReceiver5": {
      "title": "Line5",
      "type": "string",
      "maxLength": 33
    },
    "senderToReceiver6": {
      "title": "Line6",
      "type": "string",
      "maxLength": 33
    },
    "remittanceInfomation1": {
      "title": "Line1",
      "type": "string",
      "maxLength": 35
    },
    "remittanceInfomation2": {
      "title": "Line2",
      "type": "string",
      "maxLength": 33
    },
    "remittanceInfomation3": {
      "title": "Line3",
      "type": "string",
      "maxLength": 33
    },
    "remittanceInfomation4": {
      "title": "Line4",
      "type": "string",
      "maxLength": 33
    }
  },
  "additionalProperties": false,
  "required": ["settlementAccount", "settlementMeans", "ssiType", "swiftType"],
  "definitions": {
    "patternAlphaBetNumberSpace": {
      "pattern": "^[a-zA-Z0-9 ]*$"
    },
    "patternBicCode": {
      "pattern": "^(([A-Z0-9]{8})|([A-Z0-9]{11}))$"
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "swiftType": {
            "const": "MT103"
          }
        }
      },
      "then": {
        "required": [
          "accountWithInstitutionBic",
          "beneficiaryAccount",
          "beneficiaryAddress",
          "charges",
          "orderCustomAccount",
          "orderCustomAddress",
          "orderCustomName"
        ]
      }
    },
    {
      "if": {
        "description": "Cover Payment Logic #1",
        "properties": {
          "swiftType": {
            "const": "MT103"
          },
          "settlementMeans": {
            "const": "NOS"
          },
          "coveredPayment": {
            "const": true
          }
        },
        "required": ["coveredPayment"]
      },
      "then": {
        "required": ["receiversCorrespondentBic"]
      }
    },
    {
      "if": {
        "properties": {
          "swiftType": {
            "const": "MT202"
          },
          "beneficiaryBic": {
            "pattern": "^$"
          }
        }
      },
      "then": {
        "required": ["beneficiaryName"]
      }
    },
    {
      "if": {
        "properties": {
          "swiftType": {
            "const": "MT202"
          },
          "beneficiaryName": {
            "pattern": "^$"
          }
        }
      },
      "then": {
        "required": ["beneficiaryBic"]
      }
    },
    {
      "if": {
        "properties": {
          "swiftType": {
            "const": "MT202"
          },
          "settlementMeans": {
            "const": "Over-Account"
          }
        }
      },
      "then": {
        "properties": {
          "beneficiaryAccount": {
            "description": "Beneficiary Account is mandatory for SCPAY Markets"
          }
        },
        "required": ["beneficiaryAccount"]
      }
    }
  ]
}

=== lushevol/ultra-schema/src/json-schema-form/demo/ssi-form/utils/ssi-form-mock.generated.json
{
  "swiftType": "MT202",
  "ssiType": "Primary",
  "settlementMeans": "NOS",
  "settlementAccount": "CNO MAIN",
  "beneficiaryBic": "SCBLCNSXXXX",
  "beneficiaryName": "SCB CN LTD HEAD OFFICE",
  "beneficiaryCity": "China",
  "accountWithInstitutionBic": "SUOORESSXXX",
  "accountWithInstitutionName": "SCB CN LTD HEAD OFFICE",
  "orderCustomerBic": "SCBLCNSXXXX",
  "orderCustomerName": "SCB CN LTD HEAD OFFICE",
  "orderCustomerAccount": "400899993",
  "orderCustomerCity": "China",
  "orderCustomerAddress": "22F STANDARD CHARTERED TOWER SHA"
}
